Modify variable name to Load Data
This is a hotfix to correct this error message:
TypeError: __new__() got an unexpected keyword argument 'x')
The variable x has been changed to vin